name: pangbank-tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - ppanggolin
  - pygenomeviz
  - pyvis
  - ncbi-amrfinderplus
  - jupyter
  - fa2
  - python-kaleido>=1.3.0
  - plotly>=6.1.1
